spring:
  application:
    name: Arquitetura Spring
  main:
    lazy-initialization: false
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true

app:
  config:
    variavel: X