spring:
  application:
    name: Arquitetura Spring
  jpa:
    show-sql: true
  main:
    lazy-initialization: false
  datasource:
    url: jdbc:postgres://localhost:5432/livraria
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  config:
    variavel: X